// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjJQHSDGwJeco9Lyyb8FpCbEXIRXjj6E',
    appId: '1:346847254542:web:af140e138554ef64f6045f',
    messagingSenderId: '346847254542',
    projectId: 'x-project-8764c',
    authDomain: 'x-project-8764c.firebaseapp.com',
    storageBucket: 'x-project-8764c.firebasestorage.app',
    measurementId: 'G-6WYQXJ43H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1GlT-Ezpfl7W-YIHLxJVAt0xY2wL_f0',
    appId: '1:346847254542:android:4503174f17dfe57ef6045f',
    messagingSenderId: '346847254542',
    projectId: 'x-project-8764c',
    storageBucket: 'x-project-8764c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaf1JerL6gIs6-tRD_B5flWbsWANXROEY',
    appId: '1:346847254542:ios:5ec5e74f5db5e9a3f6045f',
    messagingSenderId: '346847254542',
    projectId: 'x-project-8764c',
    storageBucket: 'x-project-8764c.firebasestorage.app',
    iosBundleId: 'com.example.xProjectFlutter',
  );
}
